### ISSUE TITLE
pkg-config --cflags-only-I swig-wx returned non-zero exit status 1

### ISSUE THREAD

**Issue by k-okada** [ros/swig-wx#2]
ros-groovy-swig-wx doesn't work correctly, as reported in http://answers.ros.org/question/52023/package-swig-wx-not-found-in-rxtools-in-groovy/

**Comment by dirk-thomas** [comment]
@wjwwood Can you take a look?
I guess the package would require a manual created .pc file to work with pkg-config. I am not sure if it is worth the effort. Probably we could just drop the run_depend on swig-wx in rxtools - that would be not correct but make it work with dry packages. In hydro it is gone anyway.

**Comment by wjwwood** [comment]
@dirk-thomas I am in favor of removing the `run_depend` on swig-wx from rxtools.

**Comment by clalancette** [comment]
Closing so we can archive this repository.
